<?php
// The ID using the code on the UL is important - this is what Magento will use to hide and display the 
// Form with javascript - it should be set to display:none by default
?>
<?php $_code = $this->getMethod()->getCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
	<li>
		<div>
		    <?php echo $this->getMethod()->getConfigData('message');?>
		</div>
	</li>
</ul>
